# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-11 19:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={b'invalid': b'invalid phone number'}, max_length=20, validators=[django.core.validators.RegexValidator(b'^\\+?\\d{11,15}$')]),
        ),
    ]
