# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20190709_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
