# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190607_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('q', 'In Queue'), ('p', 'In Progress'), ('c', 'Completed')], default='q', max_length=1),
        ),
        migrations.AlterField(
            model_name='bug',
            name='vote',
            field=models.IntegerField(),
        ),
    ]
