# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 15:53
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190607_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='owner',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
