# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_bug_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='owner',
        ),
    ]
