# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-02 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0006_bug_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='bug',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbug',
            name='bugid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bugs.Bug'),
        ),
        migrations.AddField(
            model_name='userbug',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbug',
            unique_together=set([('userid', 'bugid')]),
        ),
    ]
