# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-09 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='bugid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bugs.Bug'),
        ),
    ]
