# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0009_auto_20190709_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
